server:
  port: 8762
spring:
  application:
    name: SERVICES-PROVIDE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=UTC
    username: root
    password: ok
   redis:
    host: locahost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.zb.entity
logging:
  level:
    com.zb.dao: debug

